### import model

In [1]:
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
import numpy as np

In [2]:
fname = 'finalmodel'
model = Doc2Vec.load(fname)

### Similarity Query

- doc to doc : docvecs.mostsimilar
- word to word : wv.mostsimilar

In [3]:
model.docvecs.most_similar('Lim, Chiehyeon(임치현)',topn=50)

/Users/seungheondoh/anaconda3/envs/python3.6/lib/python3.6/site-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[('Baek, Joon Sang(백준상)(2011-07~2018-03)', 0.7745015621185303),
 ('Kim, Molan(김모란)', 0.6551628112792969),
 ('Lee, Changyong(이창용)', 0.6513750553131104),
 ('Kim, KwanMyung(김관명)', 0.6358020305633545),
 ('Self, James(SelfJames Andrew)', 0.6284048557281494),
 ('Kim, Duck Young(김덕영)', 0.623092532157898),
 ('Kim, MinChung(김민중)', 0.6187516450881958),
 ('Kim, Chajoong(김차중)', 0.6160034537315369),
 ('Hong, Woonki(홍운기)', 0.6092485189437866),
 ('Kim, Yeolib(김여립)', 0.6078944802284241),
 ('Comuzzi, Marco(ComuzziMarco)', 0.6032333374023438),
 ('Woo, Hangyun(우한균)', 0.6029664278030396),
 ('Lim, Sunghoon(임성훈)', 0.5942196249961853),
 ('Kim, Namhun(김남훈)', 0.5890902280807495),
 ('Kim, Young Choon(김영춘)', 0.5881438255310059),
 ('Ko, Sungahn(고성안)', 0.5810263156890869),
 ('Hong, Hwajung(홍화정)(2015-08~2018-03)', 0.5614818930625916),
 ('Choi, Young Rok(최영록)', 0.5606884360313416),
 ('Lee, Yongjae(이용재)', 0.558128297328949),
 ('Lee, Jacob C.(이채호)', 0.5391311645507812),
 ('Zhang, Lu(ZhangLu)', 0.5141345262527466),
 ('

In [5]:
model.wv.most_similar('service',topn=30)

/Users/seungheondoh/anaconda3/envs/python3.6/lib/python3.6/site-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[('provider', 0.5643694996833801),
 ('customer', 0.5577211976051331),
 ('illinois', 0.507922887802124),
 ('negotiation', 0.4885452687740326),
 ('designer', 0.47730758786201477),
 ('healthcare', 0.47272422909736633),
 ('job', 0.4634774327278137),
 ('analytics', 0.45158061385154724),
 ('kumar', 0.4472821354866028),
 ('intelligible', 0.4457365870475769),
 ('hcooh', 0.44527387619018555),
 ('visiting', 0.44095122814178467),
 ('jamtable', 0.4401269555091858),
 ('categorization', 0.43520575761795044),
 ('mlb', 0.43239495158195496),
 ('appraisal', 0.42982110381126404),
 ('stakeholder', 0.4279237389564514),
 ('reengineering', 0.4273504614830017),
 ('apparel', 0.42465072870254517),
 ('vispark', 0.42312824726104736),
 ('dapas', 0.4227660000324249),
 ('favorite', 0.4202030301094055),
 ('workflow', 0.4190344214439392),
 ('joseph', 0.4190210700035095),
 ('yba0', 0.4177064299583435),
 ('toolsuite', 0.4176987409591675),
 ('tl6i4s', 0.41569051146507263),
 ('antecedent', 0.4152489900588989),
 ('grouping

### documents vector, docvecs

- model.docvecs.doctags : documents tag의 정보를 알려준다
- index2entity : 전체 documents tag를 조회시켜준다.
- index_to_doctag : index를 넣으면 해당하는 documents를 조회시켜준다
- model.docvecs[0] : 해당 index를 가지는 doctag의 vector값을 조회시켜준다
- vectors_docs : 전체 documents 에 대해서 백터값을 조회시켜준다

In [89]:
model.docvecs.doctags

{'Lee, Ki-Suk(이기석)': Doctag(offset=0, word_count=6956, doc_count=1),
 'Cha, Dong-Hyun(차동현)': Doctag(offset=1, word_count=5810, doc_count=1),
 'Ruoff, Rodney S.(RuoffRodney Scott)': Doctag(offset=2, word_count=50178, doc_count=1),
 'Lee, Dong Woog(이동욱)': Doctag(offset=3, word_count=3400, doc_count=1),
 'Lim, Sunghoon(임성훈)': Doctag(offset=4, word_count=890, doc_count=1),
 'Schultz, Thomas(SchultzThomas)': Doctag(offset=5, word_count=10542, doc_count=1),
 'Lee, Jiseok(이지석)': Doctag(offset=6, word_count=2060, doc_count=1),
 'Ghim, Cheol-Min(김철민)': Doctag(offset=7, word_count=2555, doc_count=1),
 'Kim, Hyoil(김효일)': Doctag(offset=8, word_count=3859, doc_count=1),
 'Kwon, Oh Hoon(권오훈)': Doctag(offset=9, word_count=6612, doc_count=1),
 'Park, Lee Soon(박이순)': Doctag(offset=10, word_count=18315, doc_count=1),
 'Kim, So Youn(김소연)': Doctag(offset=11, word_count=2725, doc_count=1),
 'Chung, Dongil(정동일)': Doctag(offset=12, word_count=1561, doc_count=1),
 'Moon, Hoi Ri(문회리)': Doctag(offset=13, word_c

In [91]:
model.docvecs.index2entity[0:5]

['Lee, Ki-Suk(이기석)',
 'Cha, Dong-Hyun(차동현)',
 'Ruoff, Rodney S.(RuoffRodney Scott)',
 'Lee, Dong Woog(이동욱)',
 'Lim, Sunghoon(임성훈)']

In [7]:
model.docvecs.index_to_doctag(0)

'Lee, Ki-Suk(이기석)'

In [22]:
model.docvecs[0]

array([ 2.1145732 , -1.7957437 , -5.2371173 ,  4.1247325 ,  0.1366728 ,
       -0.6542799 , -1.3371164 , -3.0730996 , -6.604471  , -4.4738245 ,
        1.2859367 , -7.965033  , -0.9919959 ,  1.9605457 ,  2.2680926 ,
       -2.3491538 ,  2.8558378 , -6.620563  , -5.5280027 ,  3.8091645 ,
       -5.684735  , -3.664803  ,  0.43474796,  4.2689114 , -1.9484177 ,
        5.662311  ,  7.025316  ,  5.5326977 , -3.686096  , -1.7908194 ,
       -3.2954679 ,  2.7696006 ,  0.6697843 ,  1.3377218 , -2.082109  ,
        2.756556  , -0.47322664, -0.0840409 ,  3.233076  , -1.17806   ,
       -1.7461    , -5.756814  , -6.904936  ,  0.9204389 ,  0.7620815 ,
        3.0186627 , -5.769196  , -1.8427515 ,  2.3183053 ,  4.008722  ,
       -1.8933985 , -5.764163  , -1.949176  , -1.4264978 ,  5.4212375 ,
       -0.3643698 , -4.7213244 , -3.7380583 , -1.8990062 , -1.4541768 ,
       -3.8073192 , -5.3041353 , -0.96399283,  4.2362237 ,  6.9478045 ,
       -3.9476511 , -0.13980144,  7.613749  ,  1.7611732 , -1.06

In [47]:
print(model.docvecs.vectors_docs.shape)
model.docvecs.vectors_docs

(258, 100)


array([[ 2.1145732 , -1.7957437 , -5.2371173 , ...,  4.091506  ,
        -0.43205956, -3.5082066 ],
       [ 1.3895963 ,  7.7819395 , -2.6706316 , ...,  0.55317837,
        -4.0451574 ,  0.75326574],
       [ 3.405862  , -1.5177987 ,  1.2614495 , ..., -6.0362034 ,
        -2.7812753 , -1.624586  ],
       ...,
       [ 2.2053251 ,  3.8199544 , -8.128843  , ..., -9.592905  ,
        -0.6701074 , -0.8908943 ],
       [-2.4395628 , -3.6177711 ,  0.79169166, ..., -2.236442  ,
         0.17776799, -1.5271902 ],
       [ 0.90241945,  3.527566  ,  0.939089  , ..., -0.795295  ,
        -0.13167168, -6.9900575 ]], dtype=float32)

### Wordvec tutorial

- vocab : 사전형태의 단어장을 보여준다
- index2entity : 전체 단어들의 list를 조회시켜준다
- word_vec : 단어에 대한 vector값을 조회시켜준다

In [99]:
model.wv.vocab

{'solution': <gensim.models.keyedvectors.Vocab at 0x1a15859198>,
 'processed': <gensim.models.keyedvectors.Vocab at 0x1a15859240>,
 'ferrimagnetic': <gensim.models.keyedvectors.Vocab at 0x1a15859278>,
 'insulator': <gensim.models.keyedvectors.Vocab at 0x1a158592b0>,
 'thin': <gensim.models.keyedvectors.Vocab at 0x1a15859320>,
 'film': <gensim.models.keyedvectors.Vocab at 0x1a15859390>,
 'microelectronic': <gensim.models.keyedvectors.Vocab at 0x1a158593c8>,
 'spin': <gensim.models.keyedvectors.Vocab at 0x1a15859438>,
 'seebeck': <gensim.models.keyedvectors.Vocab at 0x1a158594a8>,
 'energy': <gensim.models.keyedvectors.Vocab at 0x1a15859518>,
 'conversion': <gensim.models.keyedvectors.Vocab at 0x1a15859550>,
 'longitudinal': <gensim.models.keyedvectors.Vocab at 0x1a15859588>,
 'effect': <gensim.models.keyedvectors.Vocab at 0x1a158595f8>,
 'ferro': <gensim.models.keyedvectors.Vocab at 0x1a15859668>,
 'provide': <gensim.models.keyedvectors.Vocab at 0x1a158596d8>,
 'new': <gensim.models.key

In [94]:
model.wv.index2word[0]

'using'

In [48]:
model.wv.index2entity[0:5]

['using', 'high', 'nan', 'based', 'system']

In [36]:
model.wv.word_vec('using')

array([-1.5216053 , -0.43163773,  1.4994905 , -0.45531088, -0.04932936,
       -0.20742197,  0.34802753,  2.1623497 ,  1.0127887 ,  1.2186519 ,
        1.9760659 , -0.6106058 ,  0.56148016, -1.7668623 , -0.16248986,
        0.42295858,  1.0271702 , -0.07393517, -1.62722   , -0.7161775 ,
        1.1318922 , -1.2195617 , -1.0212426 , -1.2974932 ,  0.2882029 ,
        1.4383057 ,  0.31304634,  0.4263955 ,  1.9963619 , -0.6243407 ,
        0.1992423 , -0.6111358 , -0.26344973, -0.6550012 , -0.8911735 ,
       -0.90042907,  0.83621174,  0.5022581 , -1.4680791 ,  0.35035464,
       -0.81123626,  0.7182318 , -0.7968732 ,  0.7771847 , -2.1683848 ,
       -0.6788669 , -0.9066588 , -0.21344243, -1.0590075 ,  0.7891134 ,
        1.0222319 , -0.524551  , -0.45737767, -0.9138457 ,  1.0561252 ,
       -0.7973657 , -0.47318128,  1.1405967 , -0.4979965 , -1.4461582 ,
       -1.4609797 , -1.5979962 ,  0.98430663,  0.604789  ,  0.5930037 ,
        0.7415916 , -1.426702  ,  1.1531287 , -0.4233193 , -0.14

In [30]:
model.wv.vectors

array([[-1.5216053 , -0.43163773,  1.4994905 , ..., -1.3062506 ,
         1.5598185 ,  0.92525625],
       [ 0.3127792 , -0.35865504,  0.4235096 , ...,  2.560977  ,
         0.2661012 ,  1.8859038 ],
       [-0.84706444,  0.8222148 , -0.29621774, ...,  1.0092316 ,
         1.4069425 , -1.8470533 ],
       ...,
       [-0.40833414,  0.05359995,  0.07504433, ...,  0.19562906,
         0.3480018 , -0.09091871],
       [-0.12741429,  0.16290985,  0.11134022, ...,  0.5254985 ,
        -0.12801561, -0.13010262],
       [-0.11543101, -0.01349813, -0.01928155, ..., -0.07758613,
        -0.01274767,  0.04552545]], dtype=float32)

### Wordvector 와 docvec를 합치는 방법

In [88]:
docvec = model.docvecs.vectors_docs
wordvec = model.wv.vectors
totalvector = np.vstack((docvec,wordvec))
print(totalvector.shape)

(45334, 100)
